[[language]]
name = "rust"

[language.config]
cargo.features = "all"
check = { command = "clippy", extraArgs = "-w" }

[[language]]
name = "haskell"
auto-format = true

# Using default `marksman` now
# [[language]]
# name = "markdown"
# language-server = { command = "mdpls" }
# config = { markdown.preview.auto = false, markdown.preview.browser = "firefox" }

# [[language]]
# name = "python"
# file-types = ["py"]
# language-server = { command = "pyright" }

[[language]]
name = "roc"
scope = "source.roc"
file-types = ["roc"]
roots = []
indent = { tab-width = 4, unit = "    " }
comment-token = "#"

[[language]]
name = "scala"
auto-format = false # lags
formatter = { command = "scalafmt" , args = ["--stdin"] }

[[language]]
name = "rhai"
scope = "source.rhai"
grammar = "rust"
file-types = ["rhai"]
roots = []
indent = { tab-width = 4, unit = "    " }
comment-token = "//"

[[language]]
name = "rune"
scope = "source.rn"
grammar = "rust"
file-types = ["rn"]
roots = []
indent = { tab-width = 4, unit = "    " }
comment-token = "//"

[[grammar]]
name = "roc"
source = { git = "https://github.com/jawj/coffee-script", rev = "d06f568cd0d16e75740297068132bb9786642070", subpath = "src/grammar.coffee" }
