"\\N" = 'ℕ'
"\\R" = 'ℝ'
"\\all" = '∀'
"\\ex" = '∃'
"\\a" = 'α'
"\\b" = 'β'
"\\c" = 'χ'
"\\d" = '↓'
"\\e" = 'ε'
"\\g" = 'γ'
"\\i" = '∩'
"\\m" = 'μ'
"\\n" = '¬'
"\\o" = '∘'
"\\p" = 'Π'
"\\l" = 'λ'
"\\<" = '⟨'
"\\>" = '⟩'

"\\unicorn" = '🦄'
"\\crab" = '🦀'
